pragma solidity >=0.4.21 <0.6.0;

contract MeroToken{

	//Constructor


	//Set the total number of token

	//Read the the total number of  token

	//declaring state variable
	//for state variable getter function is auto generated by solidity
	uint256 public totalSupply;


	constructor() public 
	{
		//state variable :it accessible to entire contracts;
		totalSupply = 1000000;
	}
}